# Generated by Django 5.1.3 on 2024-11-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('year_of_study', models.CharField(choices=[('1st year', '1st year'), ('2nd year', '2nd year'), ('3rd year', '3rd year'), ('4th year', '4th year'), ('Masters', 'Masters'), ('PhD', 'PhD')], default='1st year', max_length=8)),
                ('shirt_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M', max_length=2)),
                ('university', models.CharField()),
                ('dietary_restrictions', models.CharField(blank=True, choices=[('None', 'None'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Gluten-Free', 'Gluten-Free')], max_length=255, null=True)),
                ('programming_skills', models.TextField()),
                ('experience_level', models.CharField(max_length=50)),
                ('hackathons_done', models.IntegerField()),
                ('interests', models.TextField()),
                ('preferred_role', models.CharField(choices=[('Analysis', 'Analysis'), ('Visualization', 'Visualization'), ('Development', 'Development'), ('Design', 'Design'), ("Don't know", "Don't know"), ("Don't care", "Don't care")], max_length=255)),
                ('objective', models.TextField()),
                ('interest_in_challenges', models.TextField()),
                ('preferred_language', models.CharField()),
                ('friend_registration', models.TextField()),
                ('preferred_team_size', models.IntegerField()),
                ('availability', models.TextField()),
                ('introduction', models.TextField()),
                ('technical_project', models.TextField()),
                ('future_excitement', models.TextField()),
                ('fun_fact', models.TextField()),
            ],
        ),
    ]
